---
title: "Time-spline DLNM"
author: "Jiacheng Min"
date: "`r Sys.Date()`"
output: pdf_document
---

# Used Packages
```{r, warning=FALSE}
packages <- c("readxl", "ggplot2", "forecast", "dplyr", "gridExtra", "writexl", 
              "tseries", "hwwntest", "dlnm", "splines", "ISOweek", "mgcv", 
              "Metrics", "demography", "seastests", "MTS", "tidyr", "grid",
              "nortest", "seastests", "splines")
invisible(lapply(packages, library, character.only = TRUE))
```

# Load data
```{r, warning=FALSE}
setwd("/Users/jiachengabelmin/Desktop/LC_DLNM/Data/Combined_data/")
Y20_64 = read_xlsx("/Users/jiachengabelmin/Desktop/LC_DLNM/Data/Combined_data/Y20_64_combined.xlsx")
Y65_74 = read_xlsx("/Users/jiachengabelmin/Desktop/LC_DLNM/Data/Combined_data/Y65_74_combined.xlsx")
Y75_84 = read_xlsx("/Users/jiachengabelmin/Desktop/LC_DLNM/Data/Combined_data/Y75_84_combined.xlsx")
Y_GE85 = read_xlsx("/Users/jiachengabelmin/Desktop/LC_DLNM/Data/Combined_data/Y_GE85_combined.xlsx")
```

# Weekly mortality rate
```{r}
Lisbon = cbind(Y20_64[,3]/Y20_64[,9],Y65_74[,3]/Y65_74[,9], 
               Y75_84[,3]/Y75_84[,9], Y_GE85[,3]/Y_GE85[,9])
colnames(Lisbon) = c('Y20_64', 'Y65_74', 'Y75_84', 'Y_GE85')
rownames(Lisbon) = Y20_64$Week
Lisbon = Lisbon * 52
```
# Load wave data
```{r}
Lisbon_wave = data.frame(cbind(Y20_64$Lisbon_hot_wave3, Y20_64$Lisbon_cold_wave3))
colnames(Lisbon_wave) = c("Lisbon_hot_wave3", "Lisbon_cold_wave3")
```

# Load functions
```{r}
files <- list.files("/Users/jiachengabelmin/Desktop/LC_DLNM/Code/Function/", pattern = "\\.R$", full.names = TRUE)
invisible(sapply(files, source))
```

## Load cross-basis matrix
```{r}
load("/Users/jiachengabelmin/Desktop/LC_DLNM/Code/Crossbasis_matrix/cb_Lisbon.RData")
```

# Expanding window sets
```{r}
sets = 10
size = 8
forecast_step = 78
start_ind = 102

expanding_window_sets <- lapply(0:(sets-1), function(i) {
  # Training set
  Lisbon_train <- Lisbon[1:(start_ind + i * size), ]
  # add time index
  Lisbon_train <- cbind(time = 1:nrow(Lisbon_train), Lisbon_train)
  Lisbon_wave_train <- Lisbon_wave[1:(start_ind + i * size), ]
  UTCI_ext.Lisbon_train <- UTCI_ext.Lisbon[1:(start_ind + i * size), ]
  
  # Smoothing cross-basis matrix (train)
  varknots <- equalknots(UTCI_ext.Lisbon_train, fun = "ns", df = 3, degree = 3)
  lagknots <- logknots(21, 3)
  Lisbon_cb_train <- crossbasis(UTCI_ext.Lisbon_train, lag = 21, 
                                argvar = list(fun = "ns", knots = varknots), 
                                arglag = list(knots = lagknots, df = 3))
  
  # Test set
  Lisbon_test <- Lisbon[(start_ind + i * size + 1):(start_ind + i * size + forecast_step), ]
  # add time index
  Lisbon_test <- cbind(time = 1:nrow(Lisbon_test), Lisbon_test)
  Lisbon_wave_test <- Lisbon_wave[(start_ind + i * size + 1):(start_ind + i * size + forecast_step), ]
  UTCI_ext.Lisbon_test <- UTCI_ext.Lisbon[(start_ind + i * size + 1):(start_ind + i * size + forecast_step), ]
  
  # Smoothing cross-basis matrix (test) *** using training set setting ***
  varknots <- equalknots(UTCI_ext.Lisbon_train, fun = "ns", df = 3, degree = 3)
  lagknots <- logknots(21, 3)
  Lisbon_cb_test <- crossbasis(UTCI_ext.Lisbon_test, lag = 21, 
                               argvar = list(fun = "ns", knots = varknots), 
                               arglag = list(knots = lagknots, df = 3)) 
  
  # Return a list of training and test sets for this iteration
  list(
    train = list(Lisbon_train = Lisbon_train, Lisbon_wave_train = Lisbon_wave_train,
                 Lisbon_cb_train = Lisbon_cb_train),
    test = list(Lisbon_test = Lisbon_test, Lisbon_wave_test = Lisbon_wave_test,
                Lisbon_cb_test = Lisbon_cb_test)
  )
})
names(expanding_window_sets) = paste0("set_", 1:sets)
```

# DLNM MAE
```{r}
dlnm_mae <- function(sets, set_index, age_col = "Y20_64", df_time = 5){
  sname <- paste0("set_", set_index)
  tr <- sets[[sname]]$train
  te <- sets[[sname]]$test

  # train
  y_tr    <- tr$Lisbon_train[[age_col]]
  time_tr <- tr$Lisbon_train$time
  hot_tr  <- tr$Lisbon_wave_train$Lisbon_hot_wave3
  cold_tr <- tr$Lisbon_wave_train$Lisbon_cold_wave3
  cb_tr   <- tr$Lisbon_cb_train

  train_df <- data.frame(
    y = y_tr, time = time_tr, hot = hot_tr, cold = cold_tr
  )
  train_df$cb <- cb_tr
  fit <- glm(y ~ cb + hot + cold + ns(time, df = df_time), 
             family = quasipoisson(), data = train_df)
  fitted_tr <- fitted(fit)

  # test
  y_te <- te$Lisbon_test[[age_col]]
  time_te <- te$Lisbon_test$time
  hot_te  <- te$Lisbon_wave_test$Lisbon_hot_wave3
  cold_te <- te$Lisbon_wave_test$Lisbon_cold_wave3
  cb_te   <- te$Lisbon_cb_test

  test_df <- data.frame(
    time = time_te, hot = hot_te, cold = cold_te
  )
  test_df$cb <- cb_te

  pred <- predict(fit, newdata = test_df, type = "response", se.fit = TRUE)
  mae  <- mean(abs(y_te - pred$fit), na.rm = TRUE)

  # output
  list(model = fit, fitted_train = fitted_tr, pred_test = pred$fit, mae = mae)
}
```

```{r}
res_list.20 <- lapply(1:10, function(i) dlnm_mae(expanding_window_sets, i, age_col = "Y20_64", df_time = 6))
mean_mae.20 <- 100*mean(sapply(res_list.20, `[[`, "mae"))

res_list.65 <- lapply(1:10, function(i) dlnm_mae(expanding_window_sets, i, age_col = "Y65_74", df_time = 6))
mean_mae.65 <- 100*mean(sapply(res_list.65, `[[`, "mae"))

res_list.75 <- lapply(1:10, function(i) dlnm_mae(expanding_window_sets, i, age_col = "Y75_84", df_time = 6))
mean_mae.75 <- 100*mean(sapply(res_list.75, `[[`, "mae"))

res_list.85 <- lapply(1:10, function(i) dlnm_mae(expanding_window_sets, i, age_col = "Y_GE85", df_time = 6))
mean_mae.85 <- 100*mean(sapply(res_list.85, `[[`, "mae"))

round(c(mean_mae.20, mean_mae.65, mean_mae.75, mean_mae.85), 4)
```




